In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df=pd.read_csv(r"C:\Users\Madhukar\Documents\Mechine_learning\Projects\Breast-Cancer-Detection-using-Machine-Learning-master\Breast-Cancer-Detection-using-Machine-Learning-master\cancer dataset.csv")

In [24]:
from sklearn.preprocessing import LabelEncoder
labelencoder_Y=LabelEncoder()
df.iloc[:,1]=labelencoder_Y.fit_transform(df.iloc[:,1].values)

In [25]:
X=df.iloc[:,2:31].values
Y=df.iloc[:,1].values 

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size=0.25, random_state=42)

In [27]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

### Logistic regression

In [45]:
# random state = 42 to keep the data same everytime when we re-run.

def logreg (X_train, Y_train):
    from sklearn.linear_model import LogisticRegression
    log=LogisticRegression (random_state=42)
    log.fit(X_train, Y_train)
    print("Logistic Regression Training Accuracy:", log.score(X_train, Y_train))
    return log

In [29]:
logrex=logreg(X_train, Y_train)

Logistic Regression Training Accuracy: 0.9859154929577465


In [30]:
# confusion matrix - Evaluation method

In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, logrex.predict(X_test))
print(cm)

[[89  0]
 [ 2 52]]


In [32]:
TP=cm[0][0]
TN=cm[1][1]
FN=cm[1][0]
FP=cm[0][1]
print("Testing accuracy of logistic regression model=", (TP+TN)/(TP+TN+FN+FP))

Testing accuracy of logistic regression model= 0.986013986013986


### Random Forest classifier

In [33]:
np.random.seed(42)
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, Y_train)
model.score(X_train, Y_train)

1.0

In [34]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, model.predict(X_test))
print(cm)

[[88  1]
 [ 4 50]]


In [35]:
TP=cm[0][0]
TN=cm[1][1]
FN=cm[1][0]
FP=cm[0][1]
print("Testing accuracy of Random Forest classifier model=", (TP+TN)/(TP+TN+FN+FP))

Testing accuracy of Random Forest classifier model= 0.965034965034965


### Decision tree classifier

In [41]:
np.random.seed(42)
from sklearn import tree
model = tree.DecisionTreeClassifier()
model = model.fit(X_train, Y_train)
model.score(X_train, Y_train)

1.0

In [42]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, model.predict(X_test))
print(cm)

[[87  2]
 [ 4 50]]


In [43]:
TP=cm[0][0]
TN=cm[1][1]
FN=cm[1][0]
FP=cm[0][1]
print("Testing accuracy of Decision tree classifier model=", (TP+TN)/(TP+TN+FN+FP))

Testing accuracy of Decision tree classifier model= 0.958041958041958


### In the above case Logistic Regression has higher accuracy compared to Decision tree and Random forest classifier because it performs better on a small version of the dataset having signal-to-noise as low (i.e. the problem is “hard” and there is little data) and also it fits a single line to divide the space into two and so performs better than a decision tree when the data is distributed in a fashion such that it can be linearly classified.